name: .NET Core Publish

on: 
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get tag and add to environment variables
        run: |
          RELEASE_VERSION="${GITHUB_REF#refs/*/}"
          echo "Tag is ${RELEASE_VERSION}"
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
      - name: Get person who pushed the commit
        run: |
          TAG_USER_NAME="${GITHUB_ACTOR}"
          echo "User name is ${TAG_USER_NAME}"
          echo "TAG_USER_NAME=${TAG_USER_NAME}" >> $GITHUB_ENV
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Test with dotnet
        run: dotnet test
      - name: Generate nuget package
        run: dotnet pack src/ZenExtensions.Slack.Models -c Release -o output -p:Version=${{ env.RELEASE_VERSION }} -p:Author=${{ env.TAG_USER_NAME }}
      - name: Publish github package
        run: dotnet nuget push output/*.nupkg --api-key ${{ secrets.ORG_PACKAGES_PUBLISH_TOKEN }} --source ${{ secrets.NUGET_PACKAGES_SOURCE }}
